# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 15ced80ec40f1413cabab48a125f7fa88574a065ba1de2c02991766b2110756d16769ccf7896b3f6ee3cc743f9c27d56da87f5613c87bb429303ca60186d1443

test:
  secret_key_base: 2f7261c6a80061f712f6206b8c08ebe0de75b945058bf5f68f024bfb9f9692f9e51dc6e6a2e9631045ba2b37e11793110101b399f57017b1c54639fb3f462615

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
